version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: ${APP_ENV:-development}
    image: laravel-react:${APP_ENV:-development}
    container_name: laravel-react-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-react-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel-react-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-react-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: laravel-react-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel-react-network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: laravel-react-redis
    restart: unless-stopped
    networks:
      - laravel-react-network
    ports:
      - "6379:6379"

networks:
  laravel-react-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 